import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import data from "../../../public/assets/data.json";
import classes from "./styles.module.css";

function Destination() {
  const [destination, setDestination] = useState(data.destinations[0].name);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={classes.content}>
        <article className={classes.textContainer}>
          <h2 className={classes.intro}>01 PICK YOUR DESTINATION</h2>
          <Image
            className={classes.imageContainer}
            src={data.destinations[0].images.png.substring(1)}
            alt="logo"
            width={170}
            height={170}
          />
          <div className={classes.navbarDestination}>
            <button>{data.destinations[0].name}</button>
            <button>{data.destinations[1].name}</button>
            <button>{data.destinations[2].name}</button>
            <button>{data.destinations[3].name}</button>
          </div>
          <h1 className={classes.title}>{data.destinations[0].name}</h1>
          <p className={classes.text}>{data.destinations[0].description}</p>
          <hr />
          <div className={classes.detailsContainer}>
            <div className={classes.detailsPair}>
              <p className={classes.detailLabel}>AVG. DISTANCE</p>
              <p className={classes.details}>{data.destinations[0].distance}</p>
            </div>
            <div className={classes.detailsPair}>
              <p className={classes.detailLabel}>EST. TRAVEL TIME</p>
              <p className={classes.details}>{data.destinations[0].travel}</p>
            </div>
          </div>
        </article>
      </main>
    </>
  );
}

export default Destination;
