import Head from "next/head";
import Image from "next/image";
import classes from "./styles.module.css";
import data from "../../../public/assets/data.json";

function Technology() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={classes.content}>
        <article className={classes.textContainer}>
          <h2 className={classes.intro}>03 SPACE LAUNCH 101</h2>
          <Image
            className={classes.imageContainer}
            src={data.technology[0].images.landscape.substring(1)}
            alt="logo"
            width={375}
            height={170}
          />
          <div className={classes.navbarDestination}>
            <button>{data.technology[0].name}</button>
            <button>{data.technology[1].name}</button>
            <button>{data.technology[2].name}</button>
          </div>
          <p className={classes.text}>THE TERMINOLOGY ...</p>
          <h1 className={classes.title}>{data.technology[0].name}</h1>
          <p className={classes.text}>{data.technology[0].description}</p>
        </article>
      </main>
    </>
  );
}

export default Technology;
