import Head from "next/head";
import Image from "next/image";
import classes from "./styles.module.css";
import { useState } from "react";
import data from "../../../public/assets/data.json";
import { useSwipeable } from "react-swipeable";

function Technology() {
  const [technologyIndex, setTechnologyIndex] = useState(0);
  const handlers = useSwipeable({
    onSwipedLeft: () => {
      if (technologyIndex != 2) setTechnologyIndex(technologyIndex + 1);
    },
    onSwipedRight: () => {
      if (technologyIndex != 0) setTechnologyIndex(technologyIndex - 1);
    },
  });
  return (
    <>
      <Head>
        <title>Technology - Space Tourism</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={classes.content}>
        <article {...handlers} className={classes.textContainer}>
          <h2 className={classes.intro}>
            <span className={classes.dirIndex}>03</span>SPACE LAUNCH 101
          </h2>
          <div className={classes.imageContainer}>
            <Image
              className={classes.image}
              src={data.technology[technologyIndex].images.landscape.substring(
                1
              )}
              alt={data.technology[technologyIndex].name}
              fill
            />
            <Image
              className={classes.image2}
              src={data.technology[technologyIndex].images.portrait.substring(
                1
              )}
              alt={data.technology[technologyIndex].name}
              fill
            />
          </div>
          <div className={classes.navbar}>
            {data.technology.map((entry, index) => (
              <button
                className={`${
                  index == technologyIndex
                    ? classes.btnNavActive
                    : classes.btnNav
                }`}
                key={index}
                onClick={() => setTechnologyIndex(index)}
              >
                {index + 1}
              </button>
            ))}
          </div>
          <div className={classes.infoContainer}>
            <p className={classes.text}>THE TERMINOLOGY ...</p>
            <h1 className={classes.title}>
              {data.technology[technologyIndex].name.toUpperCase()}
            </h1>
            <p className={classes.text2}>
              {data.technology[technologyIndex].description}
            </p>
          </div>
        </article>
      </main>
    </>
  );
}

export default Technology;
