import Head from "next/head";
import Image from "next/image";
import classes from "./styles.module.css";
import data from "../../../public/assets/data.json";

function Crew() {
  //state needed to render CrewContent with props passed in and nav functionality
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={classes.content}>
        <article className={classes.textContainer}>
          <h2 className={classes.intro}>02 MEET YOUR CREW</h2>
          <Image
            className={classes.imageContainer}
            src={data.crew[0].images.png.substring(1)}
            alt="logo"
            width={170}
            height={170}
          />
          <hr />

          <div className={classes.navbarDestination}>
            <button>{data.crew[0].name}</button>
            <button>{data.crew[1].name}</button>
            <button>{data.crew[2].name}</button>
            <button>{data.crew[3].name}</button>
          </div>
          <h1 className={classes.title}>{data.crew[0].name}</h1>
          <p className={classes.text}>{data.crew[0].role}</p>
          <p className={classes.bio}>{data.crew[0].bio}</p>
        </article>
      </main>
    </>
  );
}

export default Crew;
