import Head from "next/head";
import Image from "next/image";
import classes from "./styles.module.css";
import { useState } from "react";
import data from "../../../public/assets/data.json";
import { useSwipeable } from "react-swipeable";

function Crew() {
  const [crewIndex, setCrewIndex] = useState(0);
  //state needed to render CrewContent with props passed in and nav functionality

  const handlers = useSwipeable({
    onSwipedLeft: () => {
      if (crewIndex != 3) setCrewIndex(crewIndex + 1);
    },
    onSwipedRight: () => {
      if (crewIndex != 0) setCrewIndex(crewIndex - 1);
    },
  });
  return (
    <>
      <Head>
        <title>Crew - Space Tourism</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={classes.content}>
        <div className={classes.blur}>
          <article {...handlers} className={classes.textContainer}>
            <h2 className={classes.intro}>
              <span className={classes.dirIndex}>02</span>MEET YOUR CREW
            </h2>
            <div className={classes.imageContainer}>
              <Image
                className={classes.image}
                src={data.crew[crewIndex].images.png.substring(1)}
                alt={data.crew[crewIndex].name}
                fill
              />
            </div>
            <hr className={classes.hRule} />

            <div className={classes.navbarDestination}>
              {data.crew.map((entry, index) => (
                <button
                  className={`${
                    index == crewIndex
                      ? classes.navbarDotsActive
                      : classes.navbarDots
                  }`}
                  key={index}
                  onClick={() => setCrewIndex(index)}
                ></button>
              ))}
            </div>
            <div className={classes.infoContainer}>
              <p className={classes.text}>
                {data.crew[crewIndex].role.toUpperCase()}
              </p>
              <h1 className={classes.title}>
                {data.crew[crewIndex].name.toUpperCase()}
              </h1>
              <p className={classes.bio}>{data.crew[crewIndex].bio}</p>
            </div>
          </article>
        </div>
      </main>
    </>
  );
}

export default Crew;
